# Generated by Django 5.0 on 2024-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rasmi',
            field=models.ImageField(blank=True, upload_to='photoes/category'),
        ),
    ]
